### ISSUE TITLE
Add code examples to our docs using jsfiddle.com or something similar

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/origin-docs#11]
Let's add some simple working examples using jsfiddle.com or a similar code playground tool.

**Comment by wanderingstan** [comment]
Hey @tolmasky! I stumbled upon runkit yesterday in a [duplicate closed issue](https://github.com/OriginProtocol/platform/issues/98).  Looks very slick. 

Kind of odd, but can runkit also be used for playing with **non**-node js code? We want to demonstrate that origin.js can be used as either standalone js or as an npm package. 

Also, am I right that it is code-only? I.e. it doesn't do html/css like jsfiddle and similar?

We're still figuring out what these interactive examples should look like, but we'd love our documention examples ([for example](http://docs.originprotocol.com/#hello-world)) to have links out to interactive playgrounds.

**Comment by tonyjin** [comment]
Not sure if CodePen properly handles node, but it's worked great for HTML/CSS/client-side JS, [for example](https://codepen.io/box-platform/), which we surface in our [documentation](https://developer.box.com/docs/box-content-explorer )

**Comment by wanderingstan** [comment]
We are now unblocked on this!

@tyleryasaka fixed the exporting of `Origin` object in https://github.com/OriginProtocol/origin-js/issues/136

@joshfraser got our code a dedicated URL in https://github.com/OriginProtocol/origin-js/issues/75

New home for latest code is: **https://code.originprotocol.com/origin-js/origin-v0.5.10.js**

@acal, you want to take a stab at starting this? I think there's plenty of places that could use example code!

**Comment by gaboesquivel** [comment]
@tolmasky RunKit is really nice! 👍 

I would suggest CodePen.io for demos that require html.

**Comment by gaboesquivel** [comment]
It worked for me. What I like is that you can tweak the layout and share it https://codepen.io/gaboesquivel/pen/WJazjV?editors=1010

**Comment by micahalcorn** [comment]
First version done via #40 ✅
