### ISSUE TITLE
Need separate API section

### ISSUE THREAD

**Issue by tyleryasaka** [OriginProtocol/origin-docs#26]
Right now our origin.js API documentation is just mixed in with the rest of the docs. We have sections for things like `Users` and `Listings`, but these sections are at the same level as other sections such as `Introduction`. We really need a section called `API` that makes it clear what part of the docs pertains to the API. Either that, or we may eventually need separate documentation for the API. 🤔

**Comment by micahalcorn** [comment]
Thanks @tyleryasaka 👍

Related to https://github.com/OriginProtocol/company-website/issues/157 ☑️ 

I believe that the intended audience for the docs is DApp developers, and the developer landing page should be the definitive 'welcome, here are all of the places to go to learn/contribute/etc'. So I would think that these docs would be scaled down to focus on the API while some of the other stuff would move to the website.

**Comment by wanderingstan** [comment]
I'm going to close this for now, as it's been a while. 

That said, I'm not sure Slate is going to be the right solution for us long-term: we don't need it's feature of supporting multiple languages. Futhermore our docs site has become way more than just documenting our API methods, so the right column seems wasted most of the time.

**Comment by DanielVF** [comment]
I'm also thinking slate probably won't work long term.
