### ISSUE TITLE
Edit docs for new branching workflow

### ISSUE THREAD

**Issue by mek32390** [OriginProtocol/origin-docs#53]
http://docs.originprotocol.com/#local-development

The docs currently have instructions for how to develop locally using the `develop` branch. They should be changed to use our new branching model, using `master`.

**Comment by micahalcorn** [comment]
Thanks, @mek32390 😬 I've done this but just haven't deployed it.

**Comment by mek32390** [comment]
@micahalcorn okay, good to know!

**Comment by micahalcorn** [comment]
Finally [deployed this](https://github.com/OriginProtocol/origin-docs/commit/a9683e23ec4eaa9a74f5592b3a14d158358a8d09) 😅
